export const FETCH_PENDING = 'FETCH_PENGING'
export const FETCH_RESOLVE = 'FETCH_RESOLVE'
export const FETCH_REJECT = 'FETCH_REJECT'

// user
export const FETCH_USER_INFO = 'FETCH_USER_INFO'

// home
export const FETCH_HOME_PAGE = 'FETCH_HOME_PAGE'

// aticle
export const FETCH_ARTICLE_LIST = 'FETCH_ARTICLE_LIST'
export const FETCH_ARTICLE_DETAIL = 'FETCH_ARTICLE_DETAIL'

// repository
export const FETCH_REPOSITORY_LIST = 'FETCH_REPOSITORY_LIST'
export const FETCH_REPOSITORY_DETAIL = 'FETCH_REPOSITORY_DETAIL'
