export const FETCH_PENDING = 'FETCH_PENGING'
export const FETCH_RESOLVE = 'FETCH_RESOLVE'
export const FETCH_REJECT = 'FETCH_REJECT'

// user
export const FETCH_USER_INFO = 'FETCH_USER_INFO'
export const FETCH_USER_INFO_SAGA = 'FETCH_USER_INFO_SAGA'

// home
export const FETCH_HOME_PAGE = 'FETCH_HOME_PAGE'
export const FETCH_HOME_PAGE_SAGA = 'FETCH_HOME_PAGE_SAGA'

// aticle
export const FETCH_ARTICLE_LIST = 'FETCH_ARTICLE_LIST'
export const FETCH_ARTICLE_LIST_SAGA = 'FETCH_ARTICLE_LIST_SAGA'
export const FETCH_ARTICLE_DETAIL = 'FETCH_ARTICLE_DETAIL'
export const FETCH_ARTICLE_DETAIL_SAGA = 'FETCH_ARTICLE_DETAIL_SAGA'

// repository
export const FETCH_REPOSITORY_LIST = 'FETCH_REPOSITORY_LIST'
export const FETCH_REPOSITORY_LIST_SAGA = 'FETCH_REPOSITORY_LIST_SAGA'
export const FETCH_REPOSITORY_DETAIL = 'FETCH_REPOSITORY_DETAIL'
export const FETCH_REPOSITORY_DETAIL_SAGA = 'FETCH_REPOSITORY_DETAIL_SAGA'
